
from snakemake.remote.NCBI import RemoteProvider as NCBIRemoteProvider
NCBI = NCBIRemoteProvider(email="n.j.hindriks@st.hanze.nl")

query = '"Severe acute respiratory syndrome coronavirus 2"[Organism] AND (("27000"[SLEN] : "31000"[SLEN]) AND ("2019/01/01"[PDAT] : "2021/02/27"[PDAT])) '
accessions = NCBI.search(query, retmax=4)

input_files = expand("{acc}.fasta", acc=accessions)

rule all:
    input:
        "multifasta.fasta"

rule download_and_copy:
    input:
        NCBI.remote(input_files, db="nuccore")

    output:
        "multifasta.fasta"
    run:
        shell("cat {input} > multifasta.fasta")